"use client";

import { ArrowLeft, BarChart3, ChevronDown, Clipboard, Eye, Image as ImageIcon, Loader2, RefreshCw, Save, Send, Sparkles, Wand2 } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { EmojiPicker } from "@/components/EmojiPicker";
import { PageShell } from "@/components/PageShell";
import { getPost, updatePost } from "@/lib/posts";
import type { Post } from "@/types/post";

type FontFamilyOption = "기본" | "Pretendard" | "Noto Sans KR" | "나눔고딕" | "나눔명조" | "감성 손글씨" | "귀여운 손글씨" | "담백한 손글씨" | "카페 감성" | "문서형";
type FontSizeOption = "작게" | "기본" | "크게" | "아주 크게";
type TextAlignOption = "왼쪽" | "가운데" | "오른쪽";
type PreviewSaveStatus = "unsaved" | "saved" | "dirty";
type PolishResult = { polishedContent: string; html: string; imagePlacements: { url: string; positionHint: string; caption: string }[]; improvementSummary: string[] };
type AnalyzeResult = { totalScore: number; seoScore: number; clickScore: number; readabilityScore: number; photoScore: number; empathyScore: number; summary: string; strengths: string[]; improvements: string[]; betterTitles: string[]; recommendedKeywords: string[]; quickFixes: string[] };

const fontFamilyOptions: FontFamilyOption[] = ["기본", "Pretendard", "Noto Sans KR", "나눔고딕", "나눔명조", "감성 손글씨", "귀여운 손글씨", "담백한 손글씨", "카페 감성", "문서형"];
const fontSizeOptions: FontSizeOption[] = ["작게", "기본", "크게", "아주 크게"];
const textAlignOptions: TextAlignOption[] = ["왼쪽", "가운데", "오른쪽"];
const fontFamilyMap: Record<FontFamilyOption, string> = { 기본: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif", Pretendard: "Pretendard, system-ui, -apple-system, BlinkMacSystemFont, sans-serif", "Noto Sans KR": "'Noto Sans KR', system-ui, -apple-system, BlinkMacSystemFont, sans-serif", 나눔고딕: "'Nanum Gothic', 'Malgun Gothic', system-ui, sans-serif", 나눔명조: "'Nanum Myeongjo', Georgia, serif", "감성 손글씨": "'Nanum Pen Script', 'Comic Sans MS', cursive", "귀여운 손글씨": "'Gaegu', 'Comic Sans MS', cursive", "담백한 손글씨": "'Nanum Brush Script', 'Segoe Print', cursive", "카페 감성": "'Cafe24 Oneprettynight', Georgia, serif", 문서형: "Arial, 'Malgun Gothic', system-ui, sans-serif" };
const fontSizeMap: Record<FontSizeOption, string> = { 작게: "14px", 기본: "16px", 크게: "18px", "아주 크게": "20px" };
const textAlignMap: Record<TextAlignOption, "left" | "center" | "right"> = { 왼쪽: "left", 가운데: "center", 오른쪽: "right" };
const saveStatusText: Record<PreviewSaveStatus, string> = { unsaved: "아직 저장되지 않음", saved: "저장 완료", dirty: "변경사항 있음" };
const pointIconOptions = ["✅", "⭐", "🔥", "📌", "💡", "✨", "📝", "👍", "❤️", "🌿"];

export default function SavedDetailPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const contentRef = useRef<HTMLTextAreaElement | null>(null);
  const titleRef = useRef<HTMLTextAreaElement | null>(null);
  const previewRef = useRef<HTMLDivElement | null>(null);
  const [post, setPost] = useState<Post | null>(null);
  const [selectedTitle, setSelectedTitle] = useState("");
  const [titleCandidates, setTitleCandidates] = useState<string[]>([]);
  const [content, setContent] = useState("");
  const [captions, setCaptions] = useState<string[]>([]);
  const [contentWithImages, setContentWithImages] = useState("");
  const [generatedHtml, setGeneratedHtml] = useState("");
  const [savedPreviewHtml, setSavedPreviewHtml] = useState("");
  const [showHtmlCode, setShowHtmlCode] = useState(false);
  const [showEmojiPicker, setShowEmojiPicker] = useState(false);
  const [showTitleEmojiPicker, setShowTitleEmojiPicker] = useState(false);
  const [showSource, setShowSource] = useState(false);
  const [polishResult, setPolishResult] = useState<PolishResult | null>(null);
  const [analyzeResult, setAnalyzeResult] = useState<AnalyzeResult | null>(null);
  const [polishError, setPolishError] = useState("");
  const [analyzeError, setAnalyzeError] = useState("");
  const [fontFamily, setFontFamily] = useState<FontFamilyOption>("기본");
  const [fontSize, setFontSize] = useState<FontSizeOption>("기본");
  const [textAlign, setTextAlign] = useState<TextAlignOption>("왼쪽");
  const [highlightHeadings, setHighlightHeadings] = useState(true);
  const [boldKeySentences, setBoldKeySentences] = useState(true);
  const [showTags, setShowTags] = useState(true);
  const [showCaptions, setShowCaptions] = useState(true);
  const [wideParagraphSpacing, setWideParagraphSpacing] = useState(false);
  const [emojiHeadings, setEmojiHeadings] = useState(false);
  const [checkKeySentences, setCheckKeySentences] = useState(false);
  const [pointIcon, setPointIcon] = useState("✅");
  const [paragraphEditMode, setParagraphEditMode] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [titleLoading, setTitleLoading] = useState(false);
  const [previewSaving, setPreviewSaving] = useState(false);
  const [polishLoading, setPolishLoading] = useState(false);
  const [analyzeLoading, setAnalyzeLoading] = useState(false);
  const [error, setError] = useState("");
  const [toast, setToast] = useState("");

  const editorOptions = useMemo(() => ({ fontFamily, fontSize, textAlign, highlightHeadings, boldKeySentences, showTags, showCaptions, wideParagraphSpacing, emojiHeadings, checkKeySentences, pointIcon, captions }), [fontFamily, fontSize, textAlign, highlightHeadings, boldKeySentences, showTags, showCaptions, wideParagraphSpacing, emojiHeadings, checkKeySentences, pointIcon, captions]);
  const paragraphs = useMemo(() => splitParagraphs(content), [content]);
  const autoHtml = useMemo(() => post ? buildPublishHtml({ content, photoUrls: post.photo_urls || [], tags: post.tags || [], captions, fontFamily: fontFamilyMap[fontFamily], fontSize: fontSizeMap[fontSize], textAlign: textAlignMap[textAlign], highlightHeadings, boldKeySentences, showTags, showCaptions, wideParagraphSpacing, emojiHeadings, checkKeySentences, pointIcon }) : "", [post, content, captions, fontFamily, fontSize, textAlign, highlightHeadings, boldKeySentences, showTags, showCaptions, wideParagraphSpacing, emojiHeadings, checkKeySentences, pointIcon]);
  const previewHtml = generatedHtml || autoHtml;
  const previewSaveStatus: PreviewSaveStatus = !savedPreviewHtml ? "unsaved" : savedPreviewHtml === previewHtml ? "saved" : "dirty";
  const previewStyle = useMemo(() => ({ fontFamily: fontFamilyMap[fontFamily], fontSize: fontSizeMap[fontSize], textAlign: textAlignMap[textAlign] }), [fontFamily, fontSize, textAlign]);

  function showToast(message: string) { setToast(message); window.setTimeout(() => setToast(""), 2400); }
  async function loadPost() { setLoading(true); setError(""); try { const data = await getPost(params.id); const platform = typeof data.editor_options?.platform === "string" ? data.editor_options.platform : data.style === "threads" ? "threads" : "naver"; if (platform === "threads") { router.replace(`/saved/threads/${data.id}`); return; } const titles = data.ai_titles || []; const options = data.editor_options || {}; const savedCaptions = Array.isArray(options.captions) ? options.captions.map(String) : []; setPost(data); setSelectedTitle(data.travel_title || titles[0] || "제목 없음"); setTitleCandidates(titles.length > 0 ? titles : [data.travel_title || "제목 없음"]); setContent(data.content || ""); setCaptions((data.photo_urls || []).map((_, index) => savedCaptions[index] || `블로그 이미지 ${index + 1}`)); setPointIcon(typeof options.pointIcon === "string" ? options.pointIcon : "✅"); setContentWithImages(""); setGeneratedHtml(data.published_html || ""); setSavedPreviewHtml(data.published_html || ""); setPolishResult(null); setAnalyzeResult(null); setPolishError(""); setAnalyzeError(""); } catch (caught) { setError(caught instanceof Error ? `글을 불러오지 못했어요. ${caught.message}` : "글을 불러오지 못했어요. Supabase 연결을 확인해주세요."); } finally { setLoading(false); } }
  function getCurrentPreviewHtml() { return sanitizeGeneratedHtml(previewRef.current?.innerHTML || previewHtml); }
  function syncPreviewHtml() { setGeneratedHtml(getCurrentPreviewHtml()); }
  async function saveDraft() { if (!post) return; const html = getCurrentPreviewHtml(); setSaving(true); try { const updated = await updatePost(post.id, { travel_title: selectedTitle, ai_titles: titleCandidates, content, published_html: html, editor_options: editorOptions, html_updated_at: new Date().toISOString() }); setPost(updated); setSavedPreviewHtml(html); setGeneratedHtml(html); showToast("저장했어요."); } catch (caught) { showToast(caught instanceof Error ? `저장에 실패했어요. ${caught.message}` : "저장에 실패했어요."); } finally { setSaving(false); } }
  async function savePreview() { if (!post) return; const html = getCurrentPreviewHtml(); setPreviewSaving(true); try { const updated = await updatePost(post.id, { travel_title: selectedTitle, ai_titles: titleCandidates, published_html: html, editor_options: editorOptions, html_updated_at: new Date().toISOString() }); setPost(updated); setGeneratedHtml(html); setSavedPreviewHtml(html); showToast("미리보기를 저장했어요."); } catch (caught) { showToast(caught instanceof Error ? `미리보기 저장에 실패했어요. ${caught.message}` : "미리보기 저장에 실패했어요."); } finally { setPreviewSaving(false); } }
  async function goPublishReview() { if (!post) return; const html = getCurrentPreviewHtml(); setSaving(true); try { await updatePost(post.id, { travel_title: selectedTitle, ai_titles: titleCandidates, content, published_html: html, editor_options: editorOptions, html_updated_at: new Date().toISOString() }); router.push(`/publish/${post.id}`); } catch (caught) { showToast(caught instanceof Error ? `발행 검수 준비에 실패했어요. ${caught.message}` : "발행 검수 준비에 실패했어요."); } finally { setSaving(false); } }
  async function generateTitles() { if (!post) return; setTitleLoading(true); try { const response = await fetch("/api/generate-titles", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content, place: post.destination || "", style: post.style || "", persona: "", tags: post.tags || [], currentTitles: titleCandidates }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "제목 추천에 실패했어요."); const titles = data.titles as string[]; setTitleCandidates(titles); setSelectedTitle(titles[0] || selectedTitle); showToast("새 제목 후보를 만들었어요."); } catch (caught) { showToast(caught instanceof Error ? caught.message : "제목 추천 중 문제가 생겼어요."); } finally { setTitleLoading(false); } }
  async function copyText(text: string, message: string) { await navigator.clipboard.writeText(text); showToast(message); }
  function insertEmojiAtCursor(emoji: string) { const textarea = contentRef.current; const hasCursor = Boolean(textarea && document.activeElement === textarea); const start = hasCursor ? textarea?.selectionStart ?? content.length : content.length; const end = hasCursor ? textarea?.selectionEnd ?? content.length : content.length; const next = `${content.slice(0, start)}${emoji}${content.slice(end)}`; const nextCursor = start + emoji.length; setContent(next); setGeneratedHtml(""); if (hasCursor) { window.requestAnimationFrame(() => { contentRef.current?.focus(); contentRef.current?.setSelectionRange(nextCursor, nextCursor); }); } }
  function insertTitleEmoji(emoji: string) { const textarea = titleRef.current; const hasCursor = Boolean(textarea && document.activeElement === textarea); const start = hasCursor ? textarea?.selectionStart ?? 0 : 0; const end = hasCursor ? textarea?.selectionEnd ?? 0 : 0; const next = `${selectedTitle.slice(0, start)}${emoji}${selectedTitle.slice(end)}`; setSelectedTitle(next); window.requestAnimationFrame(() => { titleRef.current?.focus(); titleRef.current?.setSelectionRange(start + emoji.length, start + emoji.length); }); }
  function insertBodyEmoji(emoji: string) { if (previewRef.current && document.activeElement === previewRef.current) { document.execCommand("insertText", false, emoji); syncPreviewHtml(); return; } insertEmojiAtCursor(emoji); }
  function hasPreviewSelection() { const selection = window.getSelection(); return Boolean(selection && !selection.isCollapsed && previewRef.current && selection.anchorNode && previewRef.current.contains(selection.anchorNode)); }
  function applyPreviewCommand(command: string, value?: string, emptyMessage = "꾸밀 문장을 먼저 선택해주세요") { if (!hasPreviewSelection()) { showToast(emptyMessage); return; } document.execCommand(command, false, value); syncPreviewHtml(); }
  function applyPreviewFontSize(size: FontSizeOption) { const map: Record<FontSizeOption, string> = { 작게: "2", 기본: "3", 크게: "5", "아주 크게": "6" }; applyPreviewCommand("fontSize", map[size]); }
  function applyHeading() { applyPreviewCommand("formatBlock", "h2", "소제목으로 만들 문장을 선택해주세요"); }
  function applyParagraph() { applyPreviewCommand("formatBlock", "p", "일반 문단으로 되돌릴 문장을 선택해주세요"); }
  function createContentWithImages() { if (!post) return; if (!post.photo_urls || post.photo_urls.length === 0) { showToast("삽입할 사진 URL이 없어요."); return; } setContentWithImages(insertMarkdownImages(content, post.photo_urls)); showToast("사진 포함 본문 초안을 만들었어요."); }
  async function polishWithAi() { if (!post) return; setPolishLoading(true); setPolishError(""); try { const response = await fetch("/api/polish-post", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ content, titles: titleCandidates, tags: post.tags || [], photoUrls: post.photo_urls || [], options: editorOptions }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "AI 꾸미기에 실패했어요."); setPolishResult(data as PolishResult); showToast("AI가 보기 좋게 다듬었어요."); } catch (caught) { setPolishError(caught instanceof Error ? caught.message : "AI 꾸미기 중 문제가 생겼어요."); } finally { setPolishLoading(false); } }
  async function analyzePost() { if (!post) return; setAnalyzeLoading(true); setAnalyzeError(""); try { const response = await fetch("/api/analyze-post", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: selectedTitle, content, tags: post.tags || [], photoUrls: post.photo_urls || [], place: post.destination || "", style: post.style || "" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "블로그 점수 분석에 실패했어요."); setAnalyzeResult(data as AnalyzeResult); showToast("AI 블로그 코치 분석이 완료됐어요."); } catch (caught) { setAnalyzeError(caught instanceof Error ? caught.message : "분석 중 문제가 생겼어요."); } finally { setAnalyzeLoading(false); } }
  function applyPolishedContent() { if (!polishResult) return; setContent(polishResult.polishedContent); setGeneratedHtml(""); showToast("다듬어진 본문을 적용했어요."); }
  function applyPolishedHtml() { if (!polishResult) return; setGeneratedHtml(polishResult.html); showToast("HTML 미리보기를 적용했어요."); }
  useEffect(() => { loadPost(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [params.id]);
  return (
    <PageShell>
      <section className="min-h-screen bg-slate-50 pb-28">
        <header className="sticky top-0 z-30 border-b border-slate-100 bg-white/95 px-4 py-3 backdrop-blur">
          <div className="flex items-center justify-between gap-2">
            <button type="button" onClick={() => router.push("/saved")} className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-100 text-slate-700" aria-label="뒤로가기"><ArrowLeft size={19} aria-hidden="true" /></button>
            <div className="min-w-0 flex-1 text-center"><p className="truncate text-xs font-bold text-blue-600">{post?.status || "draft"}</p><p className="truncate text-sm font-black text-slate-950">모바일 에디터</p></div>
            <button type="button" onClick={saveDraft} disabled={saving || !post} className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-600 text-white disabled:opacity-50" aria-label="저장">{saving ? <Loader2 className="animate-spin" size={18} aria-hidden="true" /> : <Save size={18} aria-hidden="true" />}</button>
            <button type="button" onClick={goPublishReview} disabled={saving || !post} className="flex h-10 w-10 items-center justify-center rounded-full bg-slate-950 text-white disabled:opacity-50" aria-label="발행 검수"><Send size={18} aria-hidden="true" /></button>
          </div>
        </header>

        <div className="px-4 py-5">
          {loading && <div className="flex min-h-56 items-center justify-center rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><Loader2 className="animate-spin text-blue-600" size={28} aria-hidden="true" /></div>}
          {!loading && error && <div className="rounded-3xl border border-rose-100 bg-rose-50 p-5 text-rose-700"><p className="text-sm font-black">문제가 생겼어요</p><p className="mt-2 text-sm leading-6">{error}</p><button type="button" onClick={loadPost} className="mt-4 rounded-2xl bg-rose-600 px-4 py-3 text-sm font-bold text-white">다시 불러오기</button></div>}

          {!loading && post && <div className="space-y-4">
            <section className="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100">
              <p className="rounded-2xl bg-blue-50 px-4 py-3 text-xs font-bold leading-5 text-blue-700">미리보기에서 문단과 사진 설명, 제목을 바로 다듬을 수 있어요.</p>
              <div className="mt-4 flex items-start justify-between gap-3"><div className="min-w-0 flex-1"><label className="text-xs font-bold text-slate-400" htmlFor="selected-title">대표 제목</label><div className="mt-2 flex gap-2"><textarea ref={titleRef} id="selected-title" value={selectedTitle} onChange={(event) => setSelectedTitle(event.target.value)} className="min-h-20 flex-1 resize-y rounded-2xl border border-slate-100 bg-slate-50 p-3 text-xl font-black leading-7 text-slate-950 outline-none focus:border-blue-400 focus:bg-white" /><button type="button" onClick={() => setShowTitleEmojiPicker((value) => !value)} className="h-12 w-12 shrink-0 rounded-2xl bg-slate-100 text-lg">😊</button></div>{showTitleEmojiPicker && <div className="mt-2"><EmojiPicker onSelect={insertTitleEmoji} /></div>}<p className="mt-2 text-sm leading-6 text-slate-500">{post.destination || "장소 없음"} · {post.travel_date || "날짜 없음"} · {post.style || "스타일 없음"}</p></div><button type="button" onClick={generateTitles} disabled={titleLoading} className="flex shrink-0 items-center gap-1 rounded-2xl bg-blue-50 px-3 py-2 text-xs font-black text-blue-700 disabled:opacity-60">{titleLoading ? <Loader2 className="animate-spin" size={14} aria-hidden="true" /> : <RefreshCw size={14} aria-hidden="true" />}{titleLoading ? "추천 중" : "다시 추천"}</button></div>
              <div className="mt-4 grid gap-2">{titleCandidates.map((title) => <button key={title} type="button" onClick={() => setSelectedTitle(title)} className={`rounded-2xl px-4 py-3 text-left text-sm font-bold leading-6 transition ${selectedTitle === title ? "bg-blue-600 text-white" : "bg-slate-50 text-slate-700"}`}>{title}</button>)}</div>
            </section>

            <section className="rounded-3xl bg-white p-4 shadow-sm ring-1 ring-slate-100">
              <div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="text-base font-black text-slate-950">블로그 미리보기</h2><p className="mt-1 text-xs font-bold text-slate-400">사진과 꾸미기 옵션을 바로 확인해요.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500">{saveStatusText[previewSaveStatus]}</span></div>
              <EditorToolbar fontFamily={fontFamily} fontSize={fontSize} textAlign={textAlign} showEmojiPicker={showEmojiPicker} onToggleEmoji={() => setShowEmojiPicker((value) => !value)} onFontFamily={(value) => { setFontFamily(value); }} onFontSize={(value) => { setFontSize(value); }} onTextAlign={(value) => { setTextAlign(value); }} onBold={() => applyPreviewCommand("bold")} onColor={(value) => applyPreviewCommand("foreColor", value)} onHighlight={() => applyPreviewCommand("hiliteColor", "#fef08a")} onSelectionSize={applyPreviewFontSize} onHeading={applyHeading} onParagraph={applyParagraph} />
              {showEmojiPicker && <div className="mt-3"><EmojiPicker onSelect={insertBodyEmoji} /></div>}
              <div className="mt-3 rounded-3xl border border-slate-100 bg-white p-4 shadow-inner"><div ref={previewRef} className="publish-preview min-h-96 max-w-none outline-none" style={previewStyle} contentEditable suppressContentEditableWarning onBlur={syncPreviewHtml} dangerouslySetInnerHTML={{ __html: previewHtml }} /></div>
              <div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={savePreview} disabled={previewSaving} className="min-h-12 rounded-2xl bg-blue-600 px-3 text-sm font-bold text-white disabled:opacity-60">{previewSaving ? "저장 중" : "현재 미리보기 저장"}</button><button type="button" onClick={() => setShowSource((value) => !value)} className="min-h-12 rounded-2xl bg-slate-100 px-3 text-sm font-bold text-slate-700">{showSource ? "본문 원문 접기" : "본문 원문 보기"}</button></div>
              {showSource && <div className="mt-3 rounded-3xl bg-slate-50 p-3"><textarea ref={contentRef} value={content} onChange={(event) => { setContent(event.target.value); setGeneratedHtml(""); }} className="min-h-80 w-full resize-y rounded-2xl border border-slate-100 bg-white p-4 text-sm leading-7 text-slate-800 outline-none focus:border-blue-400" /><button type="button" onClick={saveDraft} disabled={saving} className="mt-3 min-h-11 w-full rounded-2xl bg-slate-950 px-3 text-sm font-bold text-white disabled:opacity-60">{saving ? "저장 중" : "본문 저장"}</button></div>}
            </section>

            <section className="grid grid-cols-3 gap-2"><PrimaryAction label="저장" loading={saving} icon={<Save size={17} aria-hidden="true" />} onClick={saveDraft} /><PrimaryAction label="AI 꾸미기" loading={polishLoading} icon={<Wand2 size={17} aria-hidden="true" />} onClick={polishWithAi} /><PrimaryAction label="발행 검수" loading={saving} icon={<Send size={17} aria-hidden="true" />} onClick={goPublishReview} dark /></section>
            {polishError && <ErrorCard title="AI 꾸미기에 실패했어요" message={polishError} />}
            {polishResult && <PolishResultCard result={polishResult} onApplyContent={applyPolishedContent} onApplyHtml={applyPolishedHtml} onSave={savePreview} saving={previewSaving} />}

            <details className="group rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-100">
              <summary className="flex cursor-pointer list-none items-center justify-between gap-3"><div><h2 className="text-base font-black text-slate-950">고급 편집 / 분석</h2><p className="mt-1 text-sm leading-6 text-slate-500">HTML, Markdown, 이미지 URL, 블로그 코치를 접어서 관리해요.</p></div><ChevronDown className="shrink-0 text-slate-400 transition group-open:rotate-180" size={20} aria-hidden="true" /></summary>
              <div className="mt-5 space-y-4">
                <details className="rounded-2xl bg-slate-50 p-4"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-black text-slate-800"><span className="flex items-center gap-2"><Eye size={16} aria-hidden="true" />발행용 HTML 코드</span><ChevronDown size={17} aria-hidden="true" /></summary><div className="mt-4 space-y-3"><p className="rounded-2xl bg-white px-3 py-3 text-xs font-bold leading-5 text-slate-500">문장 일부만 선택해 글자 크기·굵기·색상을 바꾸는 기능은 다음 리치 에디터 Sprint에서 연결할 예정이에요.</p><div className="grid grid-cols-2 gap-2"><button type="button" onClick={savePreview} disabled={previewSaving} className="min-h-11 rounded-2xl bg-blue-600 px-3 text-sm font-bold text-white disabled:opacity-60">{previewSaving ? "저장 중" : "미리보기 저장"}</button><button type="button" onClick={() => setShowHtmlCode((value) => !value)} className="min-h-11 rounded-2xl bg-white px-3 text-sm font-bold text-slate-700">{showHtmlCode ? "코드 숨기기" : "HTML 코드 보기"}</button></div>{showHtmlCode && <textarea value={previewHtml} onChange={(event) => setGeneratedHtml(event.target.value)} className="min-h-72 w-full rounded-2xl border border-slate-100 bg-white p-4 font-mono text-xs leading-6 text-slate-800 outline-none focus:border-blue-400" />}<div className="grid grid-cols-2 gap-2"><SecondaryAction label="HTML 복사" onClick={() => copyText(previewHtml, "HTML을 복사했어요.")} /><SecondaryAction label="본문 복사" onClick={() => copyText(content, "본문을 복사했어요.")} /></div></div></details>
                <section className="rounded-2xl bg-slate-50 p-4"><h3 className="text-sm font-black text-slate-950">Markdown 사진 포함 본문</h3><p className="mt-1 text-xs leading-5 text-slate-500">문단 사이에 Markdown 이미지 링크를 넣은 초안을 만들어요.</p><button type="button" onClick={createContentWithImages} className="mt-3 min-h-11 w-full rounded-2xl bg-slate-950 px-3 text-sm font-bold text-white">Markdown 생성</button>{contentWithImages && <div className="mt-3 space-y-2"><textarea value={contentWithImages} onChange={(event) => setContentWithImages(event.target.value)} className="min-h-72 w-full rounded-2xl border border-slate-100 bg-white p-4 text-sm leading-7 text-slate-800" /><SecondaryAction label="Markdown 복사" onClick={() => copyText(contentWithImages, "사진 포함 본문을 복사했어요.")} /></div>}</section>
                <section className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2"><ImageIcon className="text-blue-600" size={18} aria-hidden="true" /><h3 className="text-sm font-black text-slate-950">이미지 URL</h3></div>{post.photo_urls.length === 0 ? <p className="mt-3 text-sm font-semibold text-slate-400">저장된 사진 URL이 없어요.</p> : <div className="mt-3 space-y-2">{post.photo_urls.map((url, index) => <button key={url} type="button" onClick={() => copyText(url, "이미지 URL을 복사했어요.")} className="flex w-full items-center justify-between gap-3 rounded-2xl bg-white px-3 py-3 text-left text-xs font-bold text-slate-600"><span className="truncate">이미지 {index + 1}</span><Clipboard size={15} aria-hidden="true" /></button>)}</div>}</section>
                <section className="rounded-2xl bg-slate-50 p-4"><div className="flex items-center gap-2"><BarChart3 className="text-blue-600" size={18} aria-hidden="true" /><h3 className="text-sm font-black text-slate-950">AI 블로그 코치</h3></div><p className="mt-1 text-xs leading-5 text-slate-500">SEO, 클릭률, 가독성, 사진 활용, 공감도를 점수로 확인해요.</p><button type="button" onClick={analyzePost} disabled={analyzeLoading} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 rounded-2xl bg-blue-600 px-3 text-sm font-bold text-white disabled:opacity-60">{analyzeLoading ? <Loader2 className="animate-spin" size={16} aria-hidden="true" /> : <BarChart3 size={16} aria-hidden="true" />}{analyzeLoading ? "분석 중" : "블로그 점수 분석하기"}</button>{analyzeError && <ErrorCard title="분석에 실패했어요" message={analyzeError} />}{analyzeResult && <AnalyzeResultCard result={analyzeResult} />}</section>
              </div>
            </details>
          </div>}
        </div>
      </section>
      {toast && <div className="fixed bottom-24 left-1/2 z-50 w-[calc(100%-40px)] max-w-sm -translate-x-1/2 rounded-2xl bg-slate-950 px-4 py-3 text-center text-sm font-bold text-white shadow-xl">{toast}</div>}
    </PageShell>
  );
}
function EditorToolbar({ fontFamily, fontSize, textAlign, showEmojiPicker, onToggleEmoji, onFontFamily, onFontSize, onTextAlign, onBold, onColor, onHighlight, onSelectionSize, onHeading, onParagraph }: { fontFamily: FontFamilyOption; fontSize: FontSizeOption; textAlign: TextAlignOption; showEmojiPicker: boolean; onToggleEmoji: () => void; onFontFamily: (value: FontFamilyOption) => void; onFontSize: (value: FontSizeOption) => void; onTextAlign: (value: TextAlignOption) => void; onBold: () => void; onColor: (value: string) => void; onHighlight: () => void; onSelectionSize: (value: FontSizeOption) => void; onHeading: () => void; onParagraph: () => void }) {
  return <div className="rounded-3xl border border-slate-100 bg-white p-3 shadow-sm"><div className="grid grid-cols-2 gap-2"><CompactSelect label="글꼴" value={fontFamily} options={fontFamilyOptions} onChange={(value) => onFontFamily(value as FontFamilyOption)} /><CompactSelect label="기본 글자 크기" value={fontSize} options={fontSizeOptions} onChange={(value) => onFontSize(value as FontSizeOption)} /><CompactSelect label="정렬" value={textAlign} options={textAlignOptions} onChange={(value) => onTextAlign(value as TextAlignOption)} /><button type="button" onClick={onToggleEmoji} className={`min-h-12 rounded-2xl text-xs font-black ${showEmojiPicker ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-700"}`}>본문 이모지</button></div><div className="mt-2 grid grid-cols-4 gap-1.5"><button type="button" onClick={onBold} className="min-h-10 rounded-2xl bg-slate-100 text-xs font-black text-slate-700">굵게</button><button type="button" onClick={() => onColor("#ef4444")} className="min-h-10 rounded-2xl bg-red-50 text-xs font-black text-red-600">빨강</button><button type="button" onClick={() => onColor("#2563eb")} className="min-h-10 rounded-2xl bg-blue-50 text-xs font-black text-blue-600">파랑</button><button type="button" onClick={onHighlight} className="min-h-10 rounded-2xl bg-yellow-100 text-xs font-black text-yellow-700">형광펜</button></div><div className="mt-2 grid grid-cols-4 gap-1.5">{fontSizeOptions.map((size) => <button key={size} type="button" onClick={() => onSelectionSize(size)} className="min-h-10 rounded-2xl bg-slate-100 text-xs font-black text-slate-700">{size}</button>)}</div><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={onHeading} className="min-h-10 rounded-2xl bg-blue-50 text-xs font-black text-blue-700">선택 문장 소제목으로</button><button type="button" onClick={onParagraph} className="min-h-10 rounded-2xl bg-slate-100 text-xs font-black text-slate-700">일반 문단으로</button></div></div>;
}
function CompactSelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="block rounded-2xl bg-slate-100 px-3 py-2"><span className="block text-[10px] font-black text-slate-400">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full border-0 bg-transparent p-0 text-xs font-black text-slate-700 outline-none">{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
function ToggleChip({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <button type="button" onClick={() => onChange(!checked)} className={`min-h-9 rounded-2xl px-2 text-xs font-black ${checked ? "bg-blue-600 text-white" : "bg-slate-100 text-slate-600"}`}>{label}</button>; }
function ParagraphEditor({ paragraphs, onChange }: { paragraphs: string[]; onChange: (index: number, value: string) => void }) { return <div className="mt-3 space-y-2 rounded-3xl bg-slate-50 p-3">{paragraphs.map((paragraph, index) => <label key={`${index}-${paragraph.slice(0, 10)}`} className="block"><span className="text-xs font-black text-slate-400">문단 {index + 1} 수정</span><textarea value={paragraph} onChange={(event) => onChange(index, event.target.value)} className="mt-1 min-h-24 w-full rounded-2xl border border-slate-100 bg-white p-3 text-sm leading-6 text-slate-800 outline-none focus:border-blue-400" /></label>)}</div>; }
function CaptionEditor({ captions, onChange }: { captions: string[]; onChange: (index: number, value: string) => void }) { return <div className="mt-3 rounded-3xl bg-slate-50 p-3"><p className="text-xs font-black text-slate-500">사진 설명</p><div className="mt-2 space-y-2">{captions.map((caption, index) => <label key={index} className="block"><span className="text-[10px] font-bold text-slate-400">사진 {index + 1}</span><input value={caption} onChange={(event) => onChange(index, event.target.value)} className="mt-1 h-10 w-full rounded-2xl border border-slate-100 bg-white px-3 text-xs font-bold text-slate-700 outline-none focus:border-blue-400" /></label>)}</div></div>; }
function PrimaryAction({ label, loading, icon, onClick, dark = false }: { label: string; loading: boolean; icon: ReactNode; onClick: () => void; dark?: boolean }) { return <button type="button" onClick={onClick} disabled={loading} className={`flex min-h-16 flex-col items-center justify-center gap-1 rounded-3xl px-2 text-xs font-black shadow-sm disabled:opacity-60 ${dark ? "bg-slate-950 text-white" : "bg-blue-600 text-white"}`}>{loading ? <Loader2 className="animate-spin" size={17} aria-hidden="true" /> : icon}<span>{label}</span></button>; }
function SecondaryAction({ label, onClick }: { label: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex min-h-11 items-center justify-center gap-2 rounded-2xl bg-white px-3 text-sm font-bold text-slate-700 shadow-sm"><Clipboard size={15} aria-hidden="true" />{label}</button>; }
function PhotoStrip({ urls }: { urls: string[] }) { return <div className="mt-4"><div className="mb-2 flex items-center gap-2 text-sm font-black text-slate-800"><ImageIcon className="text-blue-600" size={17} aria-hidden="true" />사진</div><div className="flex gap-2 overflow-x-auto pb-1">{urls.map((url, index) => <div key={url} className="w-24 shrink-0 rounded-2xl bg-slate-100 p-1">{/* eslint-disable-next-line @next/next/no-img-element */}<img src={url} alt={`블로그 이미지 ${index + 1}`} className="aspect-square w-full rounded-xl object-cover" /><p className="mt-1 truncate px-1 text-[10px] font-bold text-slate-400">{index + 1}번</p></div>)}</div></div>; }
function ErrorCard({ title, message }: { title: string; message: string }) { return <div className="mt-4 rounded-2xl border border-rose-100 bg-rose-50 p-4 text-sm leading-6 text-rose-700"><p className="font-black">{title}</p><p className="mt-1">{message}</p></div>; }
function PolishResultCard({ result, onApplyContent, onApplyHtml, onSave, saving }: { result: PolishResult; onApplyContent: () => void; onApplyHtml: () => void; onSave: () => void; saving: boolean }) { return <details className="rounded-3xl border border-blue-100 bg-blue-50 p-4" open><summary className="flex cursor-pointer list-none items-center justify-between"><div><p className="text-sm font-black text-blue-800">AI 꾸미기 결과</p><p className="mt-1 text-xs leading-5 text-blue-700">적용할 항목만 빠르게 반영하세요.</p></div><Sparkles className="text-blue-600" size={18} aria-hidden="true" /></summary><div className="mt-4 space-y-3"><div className="rounded-2xl bg-white p-4"><h3 className="text-sm font-black text-slate-950">개선 요약</h3><ul className="mt-2 space-y-1 text-sm leading-6 text-slate-600">{result.improvementSummary.map((item) => <li key={item}>- {item}</li>)}</ul></div><div className="grid grid-cols-3 gap-2"><button type="button" onClick={onApplyContent} className="min-h-11 rounded-2xl bg-blue-600 px-2 text-xs font-black text-white">본문 적용</button><button type="button" onClick={onApplyHtml} className="min-h-11 rounded-2xl bg-slate-950 px-2 text-xs font-black text-white">HTML 적용</button><button type="button" onClick={onSave} disabled={saving} className="min-h-11 rounded-2xl bg-white px-2 text-xs font-black text-blue-700 disabled:opacity-60">{saving ? "저장 중" : "미리보기 저장"}</button></div><textarea value={result.polishedContent} readOnly className="min-h-56 w-full rounded-2xl border border-blue-100 bg-white p-4 text-sm leading-7 text-slate-800" /></div></details>; }
function AnalyzeResultCard({ result }: { result: AnalyzeResult }) { const scores = [{ label: "SEO", value: result.seoScore }, { label: "클릭률 예상", value: result.clickScore }, { label: "가독성", value: result.readabilityScore }, { label: "사진 활용", value: result.photoScore }, { label: "공감도", value: result.empathyScore }]; return <div className="mt-4 space-y-4"><div className="rounded-3xl bg-slate-950 p-5 text-white"><p className="text-sm font-bold text-blue-200">총점</p><div className="mt-2 flex items-end gap-2"><span className="text-5xl font-black">{result.totalScore}</span><span className="pb-1 text-sm font-bold text-slate-300">/ 100</span></div><p className="mt-3 text-sm leading-6 text-slate-200">{result.summary}</p></div><div className="grid gap-3">{scores.map((score) => <ScoreRow key={score.label} label={score.label} value={score.value} />)}</div><CoachList title="강점" items={result.strengths} tone="blue" /><CoachList title="개선 제안" items={result.improvements} tone="amber" /><CoachList title="더 나은 제목 후보" items={result.betterTitles} tone="blue" /><div className="rounded-2xl bg-white p-4"><h3 className="text-sm font-black text-slate-950">추천 키워드</h3><div className="mt-3 flex flex-wrap gap-2">{result.recommendedKeywords.length === 0 ? <span className="text-sm font-semibold text-slate-400">추천 키워드가 없어요.</span> : result.recommendedKeywords.map((keyword) => <span key={keyword} className="rounded-full bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">#{keyword}</span>)}</div></div><CoachList title="빠른 수정 제안" items={result.quickFixes} tone="slate" /></div>; }
function ScoreRow({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl bg-white p-4"><div className="flex items-center justify-between gap-3"><span className="text-sm font-black text-slate-800">{label}</span><span className="text-sm font-black text-blue-700">{value}점</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-blue-500" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div></div>; }
function CoachList({ title, items, tone }: { title: string; items: string[]; tone: "blue" | "amber" | "slate" }) { const toneClass = { blue: "bg-blue-50 text-blue-800", amber: "bg-amber-50 text-amber-800", slate: "bg-white text-slate-700" }[tone]; return <div className={`rounded-2xl p-4 ${toneClass}`}><h3 className="text-sm font-black">{title}</h3>{items.length === 0 ? <p className="mt-2 text-sm leading-6 opacity-70">표시할 항목이 없어요.</p> : <ul className="mt-2 space-y-2 text-sm leading-6">{items.map((item) => <li key={item}>- {item}</li>)}</ul>}</div>; }
function splitParagraphs(value: string) { return value.split(/\n{2,}/).filter((part) => part.trim().length > 0); }
function insertMarkdownImages(content: string, urls: string[]) { const paragraphs = splitParagraphs(content); if (paragraphs.length === 0 || urls.length === 0) return content; const insertions = chooseImageInsertions(paragraphs, urls); const output: string[] = []; paragraphs.forEach((paragraph, index) => { output.push(paragraph); (insertions.get(index) || []).forEach((imageUrl) => output.push(`![블로그 이미지 ${urls.indexOf(imageUrl) + 1}](${imageUrl})`)); }); return output.join("\n\n"); }
function chooseImageInsertions(paragraphs: string[], urls: string[]) { const insertions = new Map<number, string[]>(); if (paragraphs.length === 0) return insertions; urls.forEach((url, index) => { const target = urls.length > paragraphs.length && index >= paragraphs.length ? paragraphs.length - 1 : Math.min(paragraphs.length - 1, Math.floor(((index + 1) * paragraphs.length) / (urls.length + 1))); const current = insertions.get(target) || []; current.push(url); insertions.set(target, current); }); return insertions; }
function buildPublishHtml({ content, photoUrls, tags, captions, fontFamily, fontSize, textAlign, highlightHeadings, boldKeySentences, showTags, showCaptions, wideParagraphSpacing, emojiHeadings, checkKeySentences, pointIcon }: { content: string; photoUrls: string[]; tags: string[]; captions: string[]; fontFamily: string; fontSize: string; textAlign: "left" | "center" | "right"; highlightHeadings: boolean; boldKeySentences: boolean; showTags: boolean; showCaptions: boolean; wideParagraphSpacing: boolean; emojiHeadings: boolean; checkKeySentences: boolean; pointIcon: string }) { const paragraphs = splitParagraphs(content); const insertions = chooseImageInsertions(paragraphs, photoUrls); const blocks: string[] = []; paragraphs.forEach((paragraph, index) => { blocks.push(renderTextBlock(paragraph, { highlightHeadings, boldKeySentences, wideParagraphSpacing, emojiHeadings, checkKeySentences, pointIcon })); (insertions.get(index) || []).forEach((imageUrl) => { const imageNumber = photoUrls.indexOf(imageUrl) + 1; blocks.push(renderImageBlock(imageUrl, imageNumber, captions[imageNumber - 1] || `블로그 이미지 ${imageNumber}`, showCaptions)); }); }); if (showTags && tags.length > 0) blocks.push(`<p style="margin-top:28px;color:#059669;font-weight:700;">${tags.map((tag) => `#${escapeHtml(tag)}`).join(" ")}</p>`); return `<div style="font-family:${escapeAttribute(fontFamily)};font-size:${escapeAttribute(fontSize)};text-align:${textAlign};line-height:1.85;color:#1f2937;">\n${blocks.join("\n")}\n</div>`; }
function renderTextBlock(text: string, options: { highlightHeadings: boolean; boldKeySentences: boolean; wideParagraphSpacing: boolean; emojiHeadings: boolean; checkKeySentences: boolean; pointIcon: string }) { const normalized = text.trim(); const html = escapeHtml(stripHeadingMarks(normalized)).replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>"); if (looksLikeHeading(normalized)) { const heading = options.emojiHeadings && !/^\p{Emoji}/u.test(html) ? `✨ ${html}` : html; const style = options.highlightHeadings ? "margin:30px 0 12px;font-size:1.28em;font-weight:800;color:#111827;border-left:4px solid #10b981;padding-left:12px;" : "margin:28px 0 12px;font-size:1.18em;font-weight:700;color:#111827;"; return `<h2 style="${style}">${heading}</h2>`; } const margin = options.wideParagraphSpacing ? "0 0 28px" : "0 0 18px"; const body = options.boldKeySentences ? emphasizeKeySentence(html, options.checkKeySentences, options.pointIcon) : html; return `<p style="margin:${margin};white-space:pre-wrap;">${body}</p>`; }
function renderImageBlock(url: string, imageNumber: number, captionText: string, showCaptions: boolean) { const safeUrl = escapeAttribute(url); const caption = showCaptions ? `<figcaption style="margin-top:8px;text-align:center;color:#6b7280;font-size:0.86em;">${escapeHtml(captionText)}</figcaption>` : ""; return `<figure style="margin:24px 0;text-align:center;"><img src="${safeUrl}" alt="${escapeAttribute(captionText || `블로그 이미지 ${imageNumber}`)}" style="max-width:100%;height:auto;border-radius:12px;" />${caption}</figure>`; }
function looksLikeHeading(text: string) { const trimmed = text.trim(); if (/^#{1,3}\s+/.test(trimmed)) return true; if (/^\[[^\]]{1,30}\]$/.test(trimmed)) return true; return trimmed.length <= 24 && !/[.!?。！？]$/.test(trimmed); }
function stripHeadingMarks(text: string) { return text.replace(/^#{1,3}\s+/, "").replace(/^\[|\]$/g, ""); }
function emphasizeKeySentence(escapedText: string, addCheck: boolean, pointIcon: string) { const sentences = escapedText.split(/(?<=[.!?。！？요다])\s+/); if (sentences.length < 2) return escapedText; const targetIndex = sentences.findIndex((sentence) => sentence.length >= 18 && sentence.length <= 90); if (targetIndex < 0) return escapedText; sentences[targetIndex] = `<strong>${addCheck ? `${pointIcon} ` : ""}${sentences[targetIndex]}</strong>`; return sentences.join(" "); }
function sanitizeGeneratedHtml(html: string) { return html.replace(/```/g, "").replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>").replace(/(^|>|\n)##\s*([^<\n]+)/g, "$1<h2>$2</h2>"); }
function escapeHtml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }
function escapeAttribute(value: string) { return escapeHtml(value).replace(/`/g, "&#096;"); }







